const POINT_CHARGEMENT_CIMENCAM="POINTS DE CHARGEMENT";
const POINT_DECHARGEMENT_CIMENCAM ="POINT DE DECHARGEMENT";
const GEOFENCE ="GEOFENCE";
const ALL_VEHICLE ='All vehicles';

const PAGES=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];

module.exports={POINT_CHARGEMENT_CIMENCAM,POINT_DECHARGEMENT_CIMENCAM,ALL_VEHICLE,PAGES,GEOFENCE}